//! HIR Visitor.
//!
//! # Overview
//!
//! There is a mutable and immutable visitor trait, both are generated by a
//! `mk_visitor!` macro. The code is written following this convention:
//! - create a `visit_foo` and `super_foo` method for every HIR type.
//! - `visit_foo`, by default will simply call `super_foo`
//! - `super_foo`, by default will deconstruct the `foo` and call the
//!   appropriate `visit_*` methods on each of its fields.
//!
//! This let's you override `visit_foo` for types you are interested in and then
//! call `super_foo` in the overridden `visit_foo` to get the default behavior.
//!
//! *heavily inspired by `rustc_middle::mir::visit`.*

use std::array;

use crate::{hir::*, *};

use muonc_entity::EntityMap;
use muonc_span::prelude::*;

macro_rules! mk_visitor {
    ($visitor_name:ident $(, $mut:ident )? ) => {
        /// *See [module's documentation][crate::visit]*
        pub trait $visitor_name {
            /// Get the package being visited.
            fn pkg(&mut self) -> &$($mut)? hir::Package;

            /// Returns the current owner.
            fn cur(&mut self) -> &mut OwnerId;

            /// Make a `HirId` with the given `node_id` and `cur` as the owner.
            fn mk_id<Id: NodeType>(&mut self, node_id: Id) -> HirId<Id> {
                HirId {
                    owner: *self.cur(),
                    node_id,
                }
            }

            // overridable `visit_*` methods, call the corresponding `super_*`
            // by default.

            fn visit_package(&mut self) {
                self.super_package();
            }

            fn visit_mod(&mut self, defid: DefId) {
                self.super_mod(defid);
            }

            fn visit_span(&mut self, span: Span) {
                self.super_span(span);
            }

            fn visit_item(&mut self, item: ItemId) {
                self.super_item(item);
            }

            fn visit_fundef(&mut self, fundef: ItemId) {
                self.super_fundef(fundef);
            }

            fn visit_ident(&mut self, ident: Identifier, ctx: DefContext) {
                self.super_ident(ident, ctx);
            }

            fn visit_param(&mut self, param: ParamId) {
                self.super_param(param);
            }

            fn visit_type(&mut self, ty: TyId) {
                self.super_type(ty);
            }

            fn visit_block(&mut self, block: BlockId) {
                self.super_block(block);
            }

            fn visit_path(&mut self, path: PathId, ctx: NameContext) {
                self.super_path(path, ctx)
            }

            fn visit_stmt(&mut self, stmt: StmtId) {
                self.super_stmt(stmt);
            }

            fn visit_binding(&mut self, binding: BindingId) {
                self.super_binding(binding);
            }

            fn visit_expr(&mut self, expr: ExprId) {
                self.super_expr(expr);
            }

            fn visit_label(&mut self, label: LabelId) {
                self.super_label(label);
            }

            fn visit_fundecl(&mut self, fundecl: ItemId) {
                self.super_fundecl(fundecl);
            }

            fn visit_globdef(&mut self, globdef: ItemId) {
                self.super_globdef(globdef);
            }

            fn visit_globdecl(&mut self, globdecl: ItemId) {
                self.super_globdecl(globdecl);
            }

            fn visit_extern(&mut self, extrn: ItemId) {
                self.super_extern(extrn);
            }

            fn visit_directive(&mut self, directive: ItemId) {
                self.super_directive(directive);
            }

            fn visit_import(&mut self, path: PathId, alias: Option<Identifier>) {
                self.super_import(path, alias);
            }

            // the default behavior of the visitor, they should never be
            // overridden.

            fn super_package(&mut self) {
                *self.cur() = OwnerId(DefId::PACKAGE_DEF);

                self.visit_mod(DefId::PACKAGE_DEF);
            }

            fn super_mod(&mut self, defid: DefId) {
                let MaybeOwner::Owner(owner) = get_maybe!($($mut)?; self.pkg(), ItemId(defid)) else {
                    unreachable!("defid doesn't point to an item owner");
                };

                let mod_node = select_mut!($($mut)?; EntityMap::get_mut, EntityMap::get)(& $($mut)? owner.nodes, NodeId::ZERO);

                let (
                    Node::Package(Mod {  ref items, span })
                    | Node::Item(Item { kind: ItemKind::Directive(Directive::Mod(_, Mod { ref items, span })), ..})
                ) = *mod_node else {
                    unreachable!("not a module");
                };

                visit_item!(@seq; self, items);

                self.visit_span(span);
            }

            fn super_span(&mut self, _span: Span) {}

            fn super_item(&mut self, item: ItemId) {
                match self.pkg().get_item(item).kind {
                    ItemKind::Fundef(_) => self.visit_fundef(item),
                    ItemKind::Fundecl(_) => self.visit_fundecl(item),
                    ItemKind::Globdef(_) => self.visit_globdef(item),
                    ItemKind::Globdecl(_) => self.visit_globdecl(item),
                    ItemKind::Extern(_) => self.visit_extern(item),
                    ItemKind::Directive(_) => self.visit_directive(item),
                }
            }

            fn super_fundef(&mut self, fundef: ItemId) {
                let Item { kind: ItemKind::Fundef(Fundef { name, sig: _, body }), span } = *self.pkg().get_item(fundef) else {
                    unreachable!("not a function definition");
                };

                self.visit_ident(name, DefContext::Fundef(fundef.0));

                // we need to reborrow sig because of rust borrow checker.
                let Item { kind: ItemKind::Fundef(Fundef { ref sig, .. }), .. } = *self.pkg().get_item(fundef) else {
                    unreachable!("not a function definition");
                };

                visit_sig!(self, sig);

                self.visit_block(body);

                self.visit_span(span);
            }

            fn super_ident(&mut self, _ident: Identifier, _ctx: DefContext) {}

            fn super_param(&mut self, param: ParamId) {
                let hirid = self.mk_id(param);

                // NB: we don't visit the local because we don't need to.
                let Param { name, ty, span, local } = *self.pkg().get_node(hirid);

                let local = self.mk_id(local);
                self.visit_ident(name, DefContext::Local(local));

                self.visit_type(ty);

                self.visit_span(span);
            }

            fn super_type(&mut self, ty: TyId) {
                let hirid = self.mk_id(ty);
                let Type { ref kind, span } = *self.pkg().get_node(hirid);

                match *kind {
                    TypeKind::Path(path) => {
                        self.visit_path(path, NameContext::Use(Namespace::Type))
                    }
                    TypeKind::Pointer(_, pointee) => {
                        self.visit_type(pointee);
                    }
                    TypeKind::Funptr(ref args, ret) => {
                        for arg in args.clone() {
                            self.visit_type(arg);
                        }

                        if let Some(ret) = ret.expand() {
                            self.visit_type(ret);
                        }
                    }
                }

                self.visit_span(span);
            }

            fn super_block(&mut self, block: BlockId) {
                let hirid = self.mk_id(block);
                let Block { ref stmts, tail, span } = *self.pkg().get_node(hirid);

                for stmt in stmts.clone() {
                    self.visit_stmt(stmt);
                }

                if let Some(tail) = tail.expand() {
                    self.visit_expr(tail);
                }

                self.visit_span(span);
            }

            fn super_path(&mut self, path: PathId, ctx: NameContext) {
                let hirid = self.mk_id(path);
                let Path { ref res, ref segments, span } = *self.pkg().get_node(hirid);

                _ = res;
                _ = segments;
                _ = ctx;

                self.visit_span(span);
            }

            fn super_stmt(&mut self, stmt: StmtId) {
                let hirid = self.mk_id(stmt);
                let Stmt { ref kind, span } = *self.pkg().get_node(hirid);

                match *kind {
                    StmtKind::BindingDef(binding) => self.visit_binding(binding),
                    StmtKind::Directive(item) => self.visit_item(item),
                    StmtKind::Expr(expr) => self.visit_expr(expr),
                }

                self.visit_span(span);
            }

            fn super_binding(&mut self, binding: BindingId) {
                let hirid = self.mk_id(binding);

                // NB: we don't visit the local because we don't need to.
                let BindingDef(mutability, name, ty, expr, local, span) = *self.pkg().get_node(hirid);

                // we don't visit that it's useless i think
                _ = mutability;

                let local = self.mk_id(local);
                self.visit_ident(name, DefContext::Local(local));

                if let Some(ty) = ty.expand() {
                    self.visit_type(ty);
                }

                if let Some(expr) = expr.expand() {
                    self.visit_expr(expr);
                }

                self.visit_span(span);
            }

            fn super_expr(&mut self, expr: ExprId) {
                let hirid = self.mk_id(expr);
                let Expr { ref kind, span } = *self.pkg().get_node(hirid);

                match *kind {
                    ExprKind::Bool(_) | ExprKind::Lit(_) => {}
                    ExprKind::Path(ref path) => {
                        let path = path.clone();
                        self.visit_path(path, NameContext::Use(Namespace::Value))
                    },
                    ExprKind::Binary(lhs, _op, rhs) => {
                        self.visit_expr(lhs);
                        self.visit_expr(rhs);
                    }
                    ExprKind::Unary(_, operand) | ExprKind::Borrow(_, operand) => {
                        self.visit_expr(operand);
                    }
                    ExprKind::Call(callee, ref args) => {
                        let args = args.clone();

                        self.visit_expr(callee);

                        for arg in args {
                            self.visit_expr(arg);
                        }
                    }
                    ExprKind::If(cond, then, els) => {
                        self.visit_expr(cond);

                        self.visit_expr(then);

                        if let Some(els) = els.expand() {
                            self.visit_expr(els);
                        }
                    }
                    ExprKind::Block(label, block) => {
                        if let Some(label) = label.expand() {
                            self.visit_label(label);
                        }

                        self.visit_block(block);
                    }
                    ExprKind::Loop(label, body) => {
                        self.visit_label(label);

                        self.visit_block(body);
                    }
                    ExprKind::Return(operand) => {
                        if let Some(operand) = operand.expand() {
                            self.visit_expr(operand);
                        }
                    }
                    ExprKind::Break(label, operand) => {
                        self.visit_label(label);

                        if let Some(operand) = operand.expand() {
                            self.visit_expr(operand);
                        }
                    }
                    ExprKind::Continue(label) => {
                        self.visit_label(label);
                    }
                    ExprKind::Field(operand, member) => {
                        self.visit_expr(operand);

                        // we don't visit, or not yet at least.
                        _ = member;
                    }
                    ExprKind::Cast(op, ty) => {
                        self.visit_expr(op);

                        self.visit_type(ty);
                    }
                }

                self.visit_span(span);
            }

            fn super_label(&mut self, label: LabelId) {
                let hirid = self.mk_id(label);
                let Label { id: _, def: _, name: _, kind: _, breaked: _ } = self.pkg().get_node(hirid);
            }

            fn super_fundecl(&mut self, fundecl: ItemId) {
                let Item { kind: ItemKind::Fundecl(Fundecl {  name, ref sig }), span } = *self.pkg().get_item(fundecl) else {
                    unreachable!("not a function declaration");
                };

                visit_sig!(self, sig);

                self.visit_ident(name, DefContext::Fundecl(fundecl.0));

                self.visit_span(span);
            }

            fn super_globdef(&mut self, globdef: ItemId) {
                let Item { kind: ItemKind::Globdef(Globdef { mutability: _, name, ty, expr }), span } = *self.pkg().get_item(globdef) else {
                    unreachable!("not a function declaration");
                };

                self.visit_ident(name, DefContext::Globdef(globdef.0));

                if let Some(ty) = ty.expand() {
                    self.visit_type(ty);
                }

                self.visit_expr(expr);

                self.visit_span(span);
            }

            fn super_globdecl(&mut self, globdecl: ItemId) {
                let Item { kind: ItemKind::Globdecl(Globdecl { mutability: _, name, ty }), span } = *self.pkg().get_item(globdecl) else {
                    unreachable!("not a global declaration");
                };

                self.visit_ident(name, DefContext::Globdecl(globdecl.0));

                self.visit_type(ty);

                self.visit_span(span);
            }

            fn super_extern(&mut self, extrn: ItemId) {
                let Item { kind: ItemKind::Extern(Extern { abi: _, ref items }), span } = *self.pkg().get_item(extrn) else {
                    unreachable!("not an extern block");
                };

                visit_item!(@seq; self, items);

                self.visit_span(span);
            }

            fn super_directive(&mut self, directive: ItemId) {
                let Item { kind: ItemKind::Directive(ref dir), span } = *self.pkg().get_item(directive) else {
                    unreachable!("not a directive");
                };

                match *dir {
                    Directive::Mod(name, _) => {
                        self.visit_ident(name, DefContext::Mod(directive.0));

                        self.visit_mod(directive.0);
                        return;
                    }
                    Directive::Import { ref path, alias } => {
                        let path = path.clone();

                        self.visit_import(path, alias);
                    }
                }

                self.visit_span(span);
            }

            fn super_import(&mut self, path: PathId, alias: Option<Identifier>) {
                self.visit_path(path, NameContext::Def(DefContext::Import(alias)));
            }
        }
    };
}

macro_rules! visit_item {
    (@seq; $self:expr, $items:expr) => {
        for item in $items.clone() {
            visit_item!($self, item);
        }
    };
    ($self:expr, $item:expr) => {
        let item = $self.pkg().get_item($item);

        if item.kind.can_own() {
            let old = *$self.cur();
            *$self.cur() = OwnerId($item.0);

            $self.visit_item($item);

            *$self.cur() = old;
        } else {
            $self.visit_item($item);
        }
    };
}

macro_rules! visit_sig {
    ($self:expr, $sig:expr) => {
        let Sig {
            ref params,
            ret,
            span,
        } = *$sig;

        for param in params.clone() {
            $self.visit_param(param);
        }

        if let Some(ret) = ret.expand() {
            $self.visit_type(ret);
        }

        $self.visit_span(span);
    };
}

macro_rules! get_maybe {
    (mut; $pkg:expr, $item:expr) => {
        $pkg.mut_maybe($item)
    };

    (; $pkg:expr, $item:expr) => {
        $pkg.get_maybe($item)
    };
}

/// Select an expr based on the mutability.
macro_rules! select_mut {
    (mut; $mut_thing:expr, $immut_thing:expr) => {
        $mut_thing
    };
    (; $mut_thing:expr, $immut_thing:expr) => {
        $immut_thing
    };
}

/// The context in which a name is visited.
#[derive(Debug, Clone)]
pub enum NameContext {
    /// We are defining this identifier as the following.
    Def(DefContext),
    /// We are using this name somewhere.
    Use(Namespace),
}

/// Definition context.
#[derive(Debug, Clone)]
pub enum DefContext {
    Mod(DefId),
    Fundef(DefId),
    Fundecl(DefId),
    Globdef(DefId),
    Globdecl(DefId),
    Import(Option<Identifier>),
    Local(HirId<LocalId>),
}

/// Namespace of a name
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Namespace {
    Type,
    Value,
}

/// An helper -- a field per namespace.
#[derive(Debug, Clone)]
pub struct PerNS<T> {
    pub type_ns: T,
    pub value_ns: T,
}

impl<T> PerNS<T> {
    /// Get an iterator of the items.
    pub fn iter(self) -> array::IntoIter<T, 2> {
        [self.type_ns, self.value_ns].into_iter()
    }

    /// Get an iterator of the items with its namespace.
    pub fn iter_ns(self) -> array::IntoIter<(T, Namespace), 2> {
        [
            (self.type_ns, Namespace::Type),
            (self.value_ns, Namespace::Value),
        ]
        .into_iter()
    }
}

impl<T> PerNS<Option<T>> {
    /// An iterator over the present items
    pub fn present_items(self) -> impl Iterator<Item = T> {
        self.iter().flatten()
    }

    /// An iterator over the present items
    pub fn present_items_ns(self) -> impl Iterator<Item = (T, Namespace)> {
        self.iter_ns().filter_map(|(v, ns)| v.map(|v| (v, ns)))
    }

    /// Returns true if the PerNS is filled with `None`.
    pub fn empty(self) -> bool {
        self.type_ns.is_none() && self.value_ns.is_none()
    }
}

mk_visitor!(Visitor);
mk_visitor!(MutVisitor, mut);
